-- ----------------------------------------------------------------------------
-- Consolidated baseline, generated by the Prisma migrate engine from
-- schema.prisma (`prisma migrate diff --from-empty --to-schema --script`).
-- Regenerate this file the same way after a schema change that has not yet been
-- deployed anywhere. Custom DDL the Prisma DSL cannot express — CHECK
-- constraints, partial unique indexes, the pgvector HNSW index, array NOT NULL
-- reinstatement, and seeds — lives in the companion migration
-- `00000000000001_custom_constraints_and_indexes`, applied immediately after.
-- ----------------------------------------------------------------------------

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'LEAD', 'ENGINEER');

-- CreateEnum
CREATE TYPE "OrgRole" AS ENUM ('ORG_ADMIN', 'ORG_MEMBER');

-- CreateEnum
CREATE TYPE "WorkflowRunStatus" AS ENUM ('RUNNING', 'SUCCESS', 'FAILED', 'TIMED_OUT', 'SKIPPED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "WorkflowStepStatus" AS ENUM ('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "WorkflowTemplateStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ConfigScope" AS ENUM ('GLOBAL', 'ORGANIZATION', 'TEAM', 'CHANNEL', 'WORKFLOW_TEMPLATE');

-- CreateEnum
CREATE TYPE "ConfigAuditAction" AS ENUM ('CREATE', 'UPDATE', 'DELETE');

-- CreateEnum
CREATE TYPE "HumanStepKind" AS ENUM ('APPROVAL', 'DECISION', 'INPUT', 'REVIEW');

-- CreateEnum
CREATE TYPE "HumanStepStatus" AS ENUM ('PENDING', 'RESOLVED', 'TIMED_OUT', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EvalScoreType" AS ENUM ('BOOLEAN', 'NUMERIC', 'CATEGORICAL');

-- CreateEnum
CREATE TYPE "EvalSignalSource" AS ENUM ('GATE', 'ASSERT', 'REVIEW', 'MERGE', 'JUDGE', 'TRAJECTORY');

-- CreateEnum
CREATE TYPE "channel_open_item_status" AS ENUM ('OPEN', 'RESOLVED', 'DISMISSED');

-- CreateEnum
CREATE TYPE "ScannerPatternType" AS ENUM ('INJECTION', 'EXFILTRATION', 'SHELL_COMMAND', 'CODE_SECURITY', 'SENSITIVE_FILE');

-- CreateTable
CREATE TABLE "active_workflows" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "temporal_workflow_id" TEXT NOT NULL,
    "parent_workflow_id" TEXT,
    "work_request_id" UUID,
    "repo_id" UUID,
    "current_status" TEXT NOT NULL,
    "assigned_branch" TEXT,
    "budget_tier" TEXT NOT NULL DEFAULT 'STANDARD',
    "tokens_input_used" BIGINT NOT NULL DEFAULT 0,
    "tokens_output_used" BIGINT NOT NULL DEFAULT 0,
    "cost_usd_accrued" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "active_workflows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memory_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "scope" TEXT NOT NULL DEFAULT 'swe-lessons',
    "workflow_id" UUID,
    "repo_id" UUID,
    "channel_id" UUID,
    "team_id" UUID,
    "org_id" UUID,
    "workflow_run_id" UUID,
    "agent_key" TEXT,
    "model" TEXT,
    "cost_usd" DOUBLE PRECISION,
    "rationale" TEXT NOT NULL,
    "lesson_summary" TEXT NOT NULL,
    "embedding" vector(1536),
    "embedding_model" TEXT,
    "failure_type" TEXT,
    "metadata" JSONB,
    "skills_active" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "consolidated_at" TIMESTAMPTZ,

    CONSTRAINT "memory_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "context_snapshots" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "work_request_id" UUID NOT NULL,
    "raw_ticket_data" JSONB,
    "raw_documentation" JSONB,
    "raw_design" JSONB,
    "success_criteria" TEXT[],
    "captured_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "context_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pull_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workflow_id" UUID,
    "repo_id" UUID,
    "pr_number" INTEGER,
    "head_sha" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "ci_status" TEXT NOT NULL DEFAULT 'PENDING',

    CONSTRAINT "pull_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "personal_access_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "prefix" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ,
    "last_used_at" TIMESTAMPTZ,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "personal_access_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "connections" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" TEXT NOT NULL DEFAULT 'git_repo',
    "config" JSONB,
    "name" TEXT,
    "organization_name" TEXT,
    "repo_name" TEXT,
    "default_branch" TEXT NOT NULL DEFAULT 'main',
    "language" TEXT,
    "description" TEXT,
    "github_url" TEXT,
    "github_api_url" TEXT,
    "team_id" UUID NOT NULL,
    "executor_image" TEXT DEFAULT 'node:24-alpine',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "consolidation_enabled" BOOLEAN NOT NULL DEFAULT true,
    "gate_commands" JSONB,

    CONSTRAINT "connections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organizations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "monthly_budget_usd_cents" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teams" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "org_id" UUID NOT NULL,
    "shell_image_allowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "egress_allowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "slack_notify_channel" TEXT,
    "slack_notify_success" BOOLEAN NOT NULL DEFAULT false,
    "default_persona_prompt" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "team_memberships" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "team_id" UUID NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'ENGINEER',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "team_memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organization_memberships" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "org_id" UUID NOT NULL,
    "role" "OrgRole" NOT NULL DEFAULT 'ORG_MEMBER',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organization_memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "org_monthly_usage" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "year_month" TEXT NOT NULL,
    "cost_usd_accrued" DECIMAL(12,6) NOT NULL DEFAULT 0,
    "runs_completed" INTEGER NOT NULL DEFAULT 0,
    "tokens_input" BIGINT NOT NULL DEFAULT 0,
    "tokens_output" BIGINT NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "org_monthly_usage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "slack_workspaces" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "slack_team_id" TEXT NOT NULL,
    "name" TEXT,
    "org_id" UUID NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "bot_token_ciphertext" BYTEA,
    "bot_token_nonce" BYTEA,
    "bot_token_auth_tag" BYTEA,
    "bot_token_key_version" INTEGER,
    "bot_token_last_four" TEXT,
    "app_id" TEXT,
    "bot_user_id" TEXT,
    "installed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "slack_workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "slack_channels" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "slack_channel_id" TEXT NOT NULL,
    "workspace_id" UUID NOT NULL,
    "name" TEXT,
    "team_id" UUID NOT NULL,
    "org_id" UUID NOT NULL,
    "agent_key" TEXT NOT NULL DEFAULT 'channelAssistant',
    "ambient_enabled" BOOLEAN NOT NULL DEFAULT false,
    "ambient_cron" TEXT,
    "reactive_enabled" BOOLEAN NOT NULL DEFAULT false,
    "reactive_cron" TEXT,
    "last_reactive_check_at" TIMESTAMPTZ,
    "last_reactive_at" TIMESTAMPTZ,
    "reactive_cooldown_minutes" INTEGER,
    "reactive_lookback_minutes" INTEGER,
    "monthly_budget_usd_cents" INTEGER,
    "persona_prompt" TEXT,
    "passive_ingest_enabled" BOOLEAN NOT NULL DEFAULT false,
    "passive_ingest_cursor" TEXT,
    "is_private" BOOLEAN NOT NULL DEFAULT false,
    "org_flagging_enabled" BOOLEAN NOT NULL DEFAULT false,
    "last_org_flag_check_at" TIMESTAMPTZ,
    "org_flag_cooldown_hours" INTEGER,
    "followup_session_enabled" BOOLEAN NOT NULL DEFAULT false,
    "consolidation_enabled" BOOLEAN NOT NULL DEFAULT true,
    "consolidation_min_cluster_size" INTEGER,
    "consolidation_similarity_threshold" DOUBLE PRECISION,
    "open_item_nudge_after_hours" INTEGER,
    "open_item_nudge_cooldown_hours" INTEGER,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "slack_channels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "channel_thread_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "channel_id" UUID NOT NULL,
    "thread_ts" TEXT NOT NULL,
    "last_assistant_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_generated_template_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "channel_thread_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "channel_open_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "channel_id" UUID NOT NULL,
    "description" TEXT NOT NULL,
    "owner_user_id" TEXT,
    "status" "channel_open_item_status" NOT NULL DEFAULT 'OPEN',
    "source_ts" TEXT,
    "last_nudged_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "channel_open_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "channel_monthly_usage" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "channel_id" UUID NOT NULL,
    "year_month" TEXT NOT NULL,
    "cost_usd_accrued" DECIMAL(12,6) NOT NULL DEFAULT 0,
    "runs_completed" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "channel_monthly_usage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "channel_budget_holds" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "channel_id" UUID NOT NULL,
    "year_month" TEXT NOT NULL,
    "amount_usd" DECIMAL(12,6) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "channel_budget_holds_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "password_hash" TEXT,
    "name" TEXT,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "slack_id" TEXT,
    "role" "Role" NOT NULL DEFAULT 'ENGINEER',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferences" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "account_id" TEXT NOT NULL,
    "provider_id" TEXT NOT NULL,
    "issuer" TEXT NOT NULL,
    "user_id" UUID NOT NULL,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "id_token" TEXT,
    "access_token_expires_at" TIMESTAMPTZ,
    "refresh_token_expires_at" TIMESTAMPTZ,
    "scope" TEXT,
    "password" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "token" TEXT NOT NULL,
    "user_id" UUID NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "run_inputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "external_ticket_id" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "request_payload" TEXT NOT NULL,
    "payload" JSONB,
    "connection_id" UUID,
    "slack_message_ts" TEXT,
    "slack_channel_id" TEXT,
    "is_cross_repo" BOOLEAN NOT NULL DEFAULT false,
    "template_id" UUID,
    "template_version" INTEGER,
    "requested_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "run_inputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scheduled_work_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "cron_expression" TEXT NOT NULL,
    "repo_id" UUID NOT NULL,
    "template_id" UUID,
    "template_version" INTEGER,
    "description" TEXT NOT NULL,
    "external_ticket_prefix" TEXT NOT NULL,
    "budget_tier" TEXT NOT NULL DEFAULT 'STANDARD',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID,
    "work_request_id" UUID,
    "last_fired_at" TIMESTAMPTZ,
    "next_fire_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "scheduled_work_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_artifacts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "run_id" UUID,
    "kind" TEXT NOT NULL,
    "content_type" TEXT NOT NULL DEFAULT 'application/octet-stream',
    "size_bytes" INTEGER NOT NULL,
    "backend" TEXT NOT NULL,
    "s3_bucket" TEXT,
    "s3_key" TEXT,
    "inline_blob" BYTEA,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_artifacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_runs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workflow_id" TEXT NOT NULL,
    "template_id" UUID NOT NULL,
    "template_version" INTEGER NOT NULL,
    "work_request_id" UUID,
    "spec_snapshot" JSONB NOT NULL,
    "context_snapshot" JSONB,
    "agent_versions" JSONB,
    "pinned_settings" JSONB,
    "is_canary" BOOLEAN NOT NULL DEFAULT false,
    "baseline_sha" TEXT,
    "status" "WorkflowRunStatus" NOT NULL DEFAULT 'RUNNING',
    "started_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMPTZ,
    "cost_usd_accrued" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "tokens_input_total" BIGINT NOT NULL DEFAULT 0,
    "tokens_output_total" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "workflow_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "eval_results" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "run_id" UUID,
    "node_id" TEXT,
    "case_id" UUID,
    "eval_run_id" UUID,
    "agent_key" TEXT,
    "source" "EvalSignalSource" NOT NULL,
    "scorer" TEXT NOT NULL,
    "score_type" "EvalScoreType" NOT NULL,
    "value" DOUBLE PRECISION NOT NULL,
    "passed" BOOLEAN,
    "rationale" TEXT,
    "judge_model" TEXT,
    "cost_usd" DOUBLE PRECISION,
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "eval_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "eval_datasets" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "slug" TEXT NOT NULL,
    "scope" "ConfigScope" NOT NULL DEFAULT 'GLOBAL',
    "team_id" UUID,
    "org_id" UUID,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "eval_datasets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "eval_cases" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "dataset_id" UUID NOT NULL,
    "input" JSONB NOT NULL,
    "repo_url" TEXT NOT NULL,
    "baseline_sha" TEXT NOT NULL,
    "golden_test" TEXT NOT NULL,
    "reference" JSONB,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "flake_screened" BOOLEAN NOT NULL DEFAULT false,
    "flake_runs" INTEGER NOT NULL DEFAULT 0,
    "quarantined" BOOLEAN NOT NULL DEFAULT false,
    "source_run_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "eval_cases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "eval_runs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "dataset_id" UUID NOT NULL,
    "candidate_ref" TEXT NOT NULL,
    "baseline_ref" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'RUNNING',
    "summary" JSONB,
    "started_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMPTZ,

    CONSTRAINT "eval_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "eval_rubrics" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "slug" TEXT NOT NULL,
    "scope" "ConfigScope" NOT NULL DEFAULT 'GLOBAL',
    "team_id" UUID,
    "org_id" UUID,
    "version" INTEGER NOT NULL DEFAULT 1,
    "prompt_text" TEXT NOT NULL,
    "scale" TEXT NOT NULL DEFAULT '0..1',
    "is_built_in" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "eval_rubrics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_traces" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "run_id" UUID NOT NULL,
    "node_id" TEXT NOT NULL,
    "agent_key" TEXT NOT NULL,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "seq" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "tool_name" TEXT,
    "input_json" JSONB,
    "output_json" JSONB,
    "duration_ms" INTEGER,
    "error" TEXT,
    "model" TEXT,
    "input_tokens" INTEGER,
    "output_tokens" INTEGER,
    "cost_usd" DOUBLE PRECISION,
    "otel_trace_id" TEXT,
    "otel_span_id" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_traces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_steps" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "run_id" UUID NOT NULL,
    "node_id" TEXT NOT NULL,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "status" "WorkflowStepStatus" NOT NULL DEFAULT 'PENDING',
    "started_at" TIMESTAMPTZ,
    "ended_at" TIMESTAMPTZ,
    "inputs" JSONB,
    "outputs" JSONB,
    "error" TEXT,

    CONSTRAINT "workflow_steps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_human_steps" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "run_id" UUID NOT NULL,
    "node_id" TEXT NOT NULL,
    "signal_name" TEXT NOT NULL,
    "kind" "HumanStepKind" NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "context" JSONB,
    "options" JSONB,
    "fields" JSONB,
    "status" "HumanStepStatus" NOT NULL DEFAULT 'PENDING',
    "resolved_at" TIMESTAMPTZ,
    "resolved_by" UUID,
    "payload" JSONB,
    "requested_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeout_at" TIMESTAMPTZ,

    CONSTRAINT "workflow_human_steps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_templates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "input_schema" JSONB,
    "origin" TEXT,
    "status" "WorkflowTemplateStatus" NOT NULL DEFAULT 'DRAFT',
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "active_version" INTEGER,
    "experiment_version" INTEGER,
    "experiment_split" INTEGER,
    "webhook_token" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_template_versions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "template_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "spec" JSONB NOT NULL,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_template_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_credentials" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "provider" TEXT NOT NULL,
    "scope" "ConfigScope" NOT NULL,
    "team_id" UUID,
    "org_id" UUID,
    "api_base" TEXT,
    "api_key_ciphertext" BYTEA NOT NULL,
    "api_key_nonce" BYTEA NOT NULL,
    "api_key_auth_tag" BYTEA NOT NULL,
    "key_version" INTEGER NOT NULL DEFAULT 1,
    "last_four" TEXT NOT NULL,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "provider_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "embedding_configs" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "model_spec" TEXT NOT NULL,
    "credential_id" UUID,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "embedding_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "github_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "token_ciphertext" BYTEA,
    "token_nonce" BYTEA,
    "token_auth_tag" BYTEA,
    "token_key_version" INTEGER,
    "token_last_four" TEXT,
    "webhook_secret_ciphertext" BYTEA,
    "webhook_secret_nonce" BYTEA,
    "webhook_secret_auth_tag" BYTEA,
    "webhook_secret_key_version" INTEGER,
    "webhook_secret_last_four" TEXT,
    "oauth_client_id" TEXT,
    "oauth_client_secret_ciphertext" BYTEA,
    "oauth_client_secret_nonce" BYTEA,
    "oauth_client_secret_auth_tag" BYTEA,
    "oauth_client_secret_key_version" INTEGER,
    "oauth_client_secret_last_four" TEXT,
    "app_id" TEXT,
    "app_client_id" TEXT,
    "app_client_secret_ciphertext" BYTEA,
    "app_client_secret_nonce" BYTEA,
    "app_client_secret_auth_tag" BYTEA,
    "app_client_secret_key_version" INTEGER,
    "app_client_secret_last_four" TEXT,
    "app_private_key_ciphertext" BYTEA,
    "app_private_key_nonce" BYTEA,
    "app_private_key_auth_tag" BYTEA,
    "app_private_key_key_version" INTEGER,
    "app_private_key_last_four" TEXT,
    "app_installation_id" TEXT,
    "auth_mode" TEXT,
    "base_url" TEXT,
    "api_url" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "github_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "slack_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "client_id" TEXT,
    "client_secret_ciphertext" BYTEA,
    "client_secret_nonce" BYTEA,
    "client_secret_auth_tag" BYTEA,
    "client_secret_key_version" INTEGER,
    "client_secret_last_four" TEXT,
    "signing_secret_ciphertext" BYTEA,
    "signing_secret_nonce" BYTEA,
    "signing_secret_auth_tag" BYTEA,
    "signing_secret_key_version" INTEGER,
    "signing_secret_last_four" TEXT,
    "bot_token_ciphertext" BYTEA,
    "bot_token_nonce" BYTEA,
    "bot_token_auth_tag" BYTEA,
    "bot_token_key_version" INTEGER,
    "bot_token_last_four" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "slack_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "storage_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "backend" TEXT NOT NULL DEFAULT 'inline',
    "s3_bucket" TEXT,
    "s3_region" TEXT,
    "s3_endpoint" TEXT,
    "s3_prefix" TEXT,
    "s3_force_path_style" BOOLEAN NOT NULL DEFAULT false,
    "aws_access_key_id" TEXT,
    "aws_secret_access_key_ciphertext" BYTEA,
    "aws_secret_access_key_nonce" BYTEA,
    "aws_secret_access_key_auth_tag" BYTEA,
    "aws_secret_access_key_key_version" INTEGER,
    "aws_secret_access_key_last_four" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "storage_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_defaults" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "branch_prefix" TEXT NOT NULL DEFAULT 'auto',
    "pr_title_template" TEXT NOT NULL DEFAULT '[auto-swe] {{ticketId}}',
    "pr_body_template" TEXT NOT NULL DEFAULT '',
    "default_team_slug" TEXT NOT NULL DEFAULT 'default',
    "consolidation_enabled" BOOLEAN NOT NULL DEFAULT true,
    "consolidation_cron" TEXT NOT NULL DEFAULT '0 3 * * 0',
    "consolidation_min_cluster_size" INTEGER NOT NULL DEFAULT 3,
    "consolidation_similarity_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.85,
    "eval_schedule_enabled" BOOLEAN NOT NULL DEFAULT false,
    "eval_schedule_cron" TEXT NOT NULL DEFAULT '0 7 * * *',
    "eval_schedule_dataset_slug" TEXT NOT NULL DEFAULT 'swe-implementer-golden',
    "eval_schedule_candidate_ref" TEXT NOT NULL DEFAULT 'main',
    "eval_schedule_baseline_ref" TEXT NOT NULL DEFAULT 'last-release',
    "revalidation_enabled" BOOLEAN NOT NULL DEFAULT false,
    "revalidation_cron" TEXT NOT NULL DEFAULT '0 5 * * 0',
    "revalidation_dataset_slug" TEXT,
    "canary_enabled" BOOLEAN NOT NULL DEFAULT false,
    "canary_agent_key" TEXT,
    "canary_candidate_version" INTEGER,
    "canary_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "budget_standard_input_tokens" INTEGER NOT NULL DEFAULT 2000000,
    "budget_standard_output_tokens" INTEGER NOT NULL DEFAULT 500000,
    "budget_large_input_tokens" INTEGER NOT NULL DEFAULT 8000000,
    "budget_large_output_tokens" INTEGER NOT NULL DEFAULT 2000000,
    "budget_epic_input_tokens" INTEGER NOT NULL DEFAULT 20000000,
    "budget_epic_output_tokens" INTEGER NOT NULL DEFAULT 5000000,
    "max_tdd_iterations" INTEGER NOT NULL DEFAULT 5,
    "max_eval_iterations" INTEGER NOT NULL DEFAULT 3,
    "workspace_memory" TEXT NOT NULL DEFAULT '4g',
    "workspace_cpus" DOUBLE PRECISION NOT NULL DEFAULT 2,
    "workspace_pids_limit" INTEGER NOT NULL DEFAULT 512,
    "workspace_image" TEXT NOT NULL DEFAULT 'node:24-alpine',
    "lesson_retrieval_limit" INTEGER NOT NULL DEFAULT 5,
    "lesson_retrieval_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    "ci_wait_mode" TEXT,
    "ci_poll_interval_sec" INTEGER,
    "ci_poll_grace_sec" INTEGER,
    "ci_poll_deadline_sec" INTEGER,
    "eval_health_max_flake_rate" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "eval_health_max_stale_rate" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "eval_health_min_kappa" DOUBLE PRECISION NOT NULL DEFAULT 0.4,
    "eval_judge_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_defaults_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "google_oauth_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "client_id" TEXT,
    "client_secret_ciphertext" BYTEA,
    "client_secret_nonce" BYTEA,
    "client_secret_auth_tag" BYTEA,
    "client_secret_key_version" INTEGER,
    "client_secret_last_four" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "google_oauth_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "okta_oauth_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "issuer" TEXT,
    "client_id" TEXT,
    "client_secret_ciphertext" BYTEA,
    "client_secret_nonce" BYTEA,
    "client_secret_auth_tag" BYTEA,
    "client_secret_key_version" INTEGER,
    "client_secret_last_four" TEXT,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "okta_oauth_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issue_tracker_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "provider" TEXT,
    "instance_type" TEXT DEFAULT 'cloud',
    "base_url" TEXT,
    "email" TEXT,
    "api_token_ciphertext" BYTEA,
    "api_token_nonce" BYTEA,
    "api_token_auth_tag" BYTEA,
    "api_token_key_version" INTEGER,
    "api_token_last_four" TEXT,
    "timeout_ms" INTEGER DEFAULT 5000,
    "max_retries" INTEGER DEFAULT 3,
    "story_points_field_id" TEXT DEFAULT 'story_points',
    "epic_issue_type" TEXT DEFAULT 'Epic',
    "story_issue_type" TEXT DEFAULT 'Story',
    "default_project_key" TEXT,
    "webhook_secret_ciphertext" BYTEA,
    "webhook_secret_nonce" BYTEA,
    "webhook_secret_auth_tag" BYTEA,
    "webhook_secret_key_version" INTEGER,
    "webhook_secret_last_four" TEXT,
    "webhook_trigger_status" TEXT,
    "allow_private_network" BOOLEAN NOT NULL DEFAULT false,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issue_tracker_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "knowledge_base_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "provider" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "base_url" TEXT,
    "api_token_ciphertext" BYTEA,
    "api_token_nonce" BYTEA,
    "api_token_auth_tag" BYTEA,
    "api_token_key_version" INTEGER,
    "api_token_last_four" TEXT,
    "email" TEXT,
    "spaces" TEXT[],
    "max_pages" INTEGER DEFAULT 5,
    "allow_private_network" BOOLEAN NOT NULL DEFAULT false,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "knowledge_base_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "figma_config" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "api_token_ciphertext" BYTEA,
    "api_token_nonce" BYTEA,
    "api_token_auth_tag" BYTEA,
    "api_token_key_version" INTEGER,
    "api_token_last_four" TEXT,
    "max_nodes" INTEGER DEFAULT 12,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "figma_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "config_settings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "scope" "ConfigScope" NOT NULL,
    "team_id" UUID,
    "org_id" UUID,
    "channel_id" UUID,
    "workflow_template_id" UUID,
    "value" JSONB NOT NULL,
    "updated_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "config_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "config_permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key_pattern" TEXT NOT NULL,
    "user_id" UUID,
    "role" "Role",
    "scope" "ConfigScope" NOT NULL,
    "team_id" UUID,
    "org_id" UUID,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "config_permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "config_audit_log" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "entity_type" TEXT NOT NULL,
    "entity_id" UUID NOT NULL,
    "action" "ConfigAuditAction" NOT NULL,
    "actor_id" UUID,
    "before_json" JSONB,
    "after_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "config_audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skills" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "prompt_text" TEXT NOT NULL,
    "origin" TEXT,
    "is_built_in" BOOLEAN NOT NULL DEFAULT false,
    "is_verified" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "scope" "ConfigScope" NOT NULL DEFAULT 'GLOBAL',
    "team_id" UUID,
    "org_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "skills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scanner_patterns" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "label" TEXT NOT NULL,
    "pattern" TEXT NOT NULL,
    "flags" TEXT NOT NULL DEFAULT '',
    "type" "ScannerPatternType" NOT NULL,
    "origin" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_built_in" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "scanner_patterns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "scope" "ConfigScope" NOT NULL,
    "team_id" UUID,
    "org_id" UUID,
    "channel_id" UUID,
    "workflow_template_id" UUID,
    "version" INTEGER NOT NULL DEFAULT 1,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "model_spec" TEXT,
    "system_prompt" TEXT,
    "inherits_model_from" TEXT,
    "credential_id" UUID,
    "mcp_connection_id" UUID,
    "tool_keys" JSONB,
    "origin" TEXT,
    "is_built_in" BOOLEAN NOT NULL DEFAULT false,
    "is_verified" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_skill_refs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "agent_id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_skill_refs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_shell_audit" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "template_version_id" UUID NOT NULL,
    "team_id" UUID,
    "node_id" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "command" TEXT NOT NULL,
    "network" TEXT NOT NULL DEFAULT 'none',
    "egress_allowlist_snapshot" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "author_user_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_shell_audit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "installed_bundles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "source" TEXT,
    "content_hash" TEXT NOT NULL,
    "trust_state" TEXT NOT NULL DEFAULT 'UNVERIFIED',
    "signed_by" TEXT,
    "installed_by_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "installed_bundles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "active_workflows_temporal_workflow_id_key" ON "active_workflows"("temporal_workflow_id");

-- CreateIndex
CREATE INDEX "active_workflows_work_request_id_idx" ON "active_workflows"("work_request_id");

-- CreateIndex
CREATE INDEX "active_workflows_repo_id_assigned_branch_idx" ON "active_workflows"("repo_id", "assigned_branch");

-- CreateIndex
CREATE INDEX "memory_items_repo_id_consolidated_at_idx" ON "memory_items"("repo_id", "consolidated_at");

-- CreateIndex
CREATE INDEX "memory_items_scope_consolidated_at_idx" ON "memory_items"("scope", "consolidated_at");

-- CreateIndex
CREATE INDEX "memory_items_channel_id_consolidated_at_idx" ON "memory_items"("channel_id", "consolidated_at");

-- CreateIndex
CREATE INDEX "memory_items_team_id_consolidated_at_idx" ON "memory_items"("team_id", "consolidated_at");

-- CreateIndex
CREATE INDEX "memory_items_org_id_consolidated_at_idx" ON "memory_items"("org_id", "consolidated_at");

-- CreateIndex
CREATE INDEX "memory_items_workflow_id_idx" ON "memory_items"("workflow_id");

-- CreateIndex
CREATE INDEX "memory_items_workflow_run_id_idx" ON "memory_items"("workflow_run_id");

-- CreateIndex
CREATE UNIQUE INDEX "context_snapshots_work_request_id_key" ON "context_snapshots"("work_request_id");

-- CreateIndex
CREATE INDEX "pull_requests_workflow_id_idx" ON "pull_requests"("workflow_id");

-- CreateIndex
CREATE INDEX "pull_requests_repo_id_idx" ON "pull_requests"("repo_id");

-- CreateIndex
CREATE UNIQUE INDEX "personal_access_tokens_token_hash_key" ON "personal_access_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "personal_access_tokens_user_id_idx" ON "personal_access_tokens"("user_id");

-- CreateIndex
CREATE INDEX "connections_team_id_idx" ON "connections"("team_id");

-- CreateIndex
CREATE UNIQUE INDEX "organizations_name_key" ON "organizations"("name");

-- CreateIndex
CREATE UNIQUE INDEX "organizations_slug_key" ON "organizations"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "teams_name_key" ON "teams"("name");

-- CreateIndex
CREATE UNIQUE INDEX "teams_slug_key" ON "teams"("slug");

-- CreateIndex
CREATE INDEX "teams_org_id_idx" ON "teams"("org_id");

-- CreateIndex
CREATE INDEX "team_memberships_user_id_idx" ON "team_memberships"("user_id");

-- CreateIndex
CREATE INDEX "team_memberships_team_id_idx" ON "team_memberships"("team_id");

-- CreateIndex
CREATE UNIQUE INDEX "team_memberships_user_id_team_id_key" ON "team_memberships"("user_id", "team_id");

-- CreateIndex
CREATE INDEX "organization_memberships_org_id_idx" ON "organization_memberships"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "organization_memberships_user_id_org_id_key" ON "organization_memberships"("user_id", "org_id");

-- CreateIndex
CREATE INDEX "org_monthly_usage_org_id_idx" ON "org_monthly_usage"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "org_monthly_usage_org_id_year_month_key" ON "org_monthly_usage"("org_id", "year_month");

-- CreateIndex
CREATE UNIQUE INDEX "slack_workspaces_slack_team_id_key" ON "slack_workspaces"("slack_team_id");

-- CreateIndex
CREATE INDEX "slack_workspaces_org_id_idx" ON "slack_workspaces"("org_id");

-- CreateIndex
CREATE INDEX "slack_channels_team_id_idx" ON "slack_channels"("team_id");

-- CreateIndex
CREATE INDEX "slack_channels_org_id_idx" ON "slack_channels"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "slack_channels_workspace_id_slack_channel_id_key" ON "slack_channels"("workspace_id", "slack_channel_id");

-- CreateIndex
CREATE INDEX "channel_thread_sessions_channel_id_idx" ON "channel_thread_sessions"("channel_id");

-- CreateIndex
CREATE UNIQUE INDEX "channel_thread_sessions_channel_id_thread_ts_key" ON "channel_thread_sessions"("channel_id", "thread_ts");

-- CreateIndex
CREATE INDEX "channel_open_items_channel_id_status_idx" ON "channel_open_items"("channel_id", "status");

-- CreateIndex
CREATE INDEX "channel_monthly_usage_channel_id_idx" ON "channel_monthly_usage"("channel_id");

-- CreateIndex
CREATE UNIQUE INDEX "channel_monthly_usage_channel_id_year_month_key" ON "channel_monthly_usage"("channel_id", "year_month");

-- CreateIndex
CREATE INDEX "channel_budget_holds_channel_id_year_month_idx" ON "channel_budget_holds"("channel_id", "year_month");

-- CreateIndex
CREATE INDEX "channel_budget_holds_channel_id_expires_at_idx" ON "channel_budget_holds"("channel_id", "expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_slack_id_key" ON "users"("slack_id");

-- CreateIndex
CREATE INDEX "accounts_user_id_idx" ON "accounts"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "accounts_issuer_account_id_key" ON "accounts"("issuer", "account_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "sessions"("token");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "sessions"("user_id");

-- CreateIndex
CREATE INDEX "verifications_identifier_idx" ON "verifications"("identifier");

-- CreateIndex
CREATE INDEX "run_inputs_connection_id_idx" ON "run_inputs"("connection_id");

-- CreateIndex
CREATE INDEX "run_inputs_requested_by_id_idx" ON "run_inputs"("requested_by_id");

-- CreateIndex
CREATE INDEX "run_inputs_external_ticket_id_idx" ON "run_inputs"("external_ticket_id");

-- CreateIndex
CREATE INDEX "scheduled_work_requests_repo_id_idx" ON "scheduled_work_requests"("repo_id");

-- CreateIndex
CREATE INDEX "scheduled_work_requests_template_id_idx" ON "scheduled_work_requests"("template_id");

-- CreateIndex
CREATE INDEX "scheduled_work_requests_created_by_id_idx" ON "scheduled_work_requests"("created_by_id");

-- CreateIndex
CREATE INDEX "scheduled_work_requests_work_request_id_idx" ON "scheduled_work_requests"("work_request_id");

-- CreateIndex
CREATE INDEX "workflow_artifacts_run_id_idx" ON "workflow_artifacts"("run_id");

-- CreateIndex
CREATE UNIQUE INDEX "workflow_runs_workflow_id_key" ON "workflow_runs"("workflow_id");

-- CreateIndex
CREATE INDEX "workflow_runs_template_id_idx" ON "workflow_runs"("template_id");

-- CreateIndex
CREATE INDEX "workflow_runs_work_request_id_idx" ON "workflow_runs"("work_request_id");

-- CreateIndex
CREATE INDEX "eval_results_run_id_idx" ON "eval_results"("run_id");

-- CreateIndex
CREATE INDEX "eval_results_case_id_idx" ON "eval_results"("case_id");

-- CreateIndex
CREATE INDEX "eval_results_eval_run_id_idx" ON "eval_results"("eval_run_id");

-- CreateIndex
CREATE INDEX "eval_results_scorer_created_at_idx" ON "eval_results"("scorer", "created_at");

-- CreateIndex
CREATE INDEX "eval_results_source_created_at_idx" ON "eval_results"("source", "created_at");

-- CreateIndex
CREATE INDEX "eval_datasets_scope_team_id_idx" ON "eval_datasets"("scope", "team_id");

-- CreateIndex
CREATE INDEX "eval_datasets_slug_idx" ON "eval_datasets"("slug");

-- CreateIndex
CREATE INDEX "eval_cases_dataset_id_idx" ON "eval_cases"("dataset_id");

-- CreateIndex
CREATE INDEX "eval_runs_dataset_id_started_at_idx" ON "eval_runs"("dataset_id", "started_at");

-- CreateIndex
CREATE INDEX "eval_rubrics_scope_slug_idx" ON "eval_rubrics"("scope", "slug");

-- CreateIndex
CREATE INDEX "agent_traces_run_id_node_id_idx" ON "agent_traces"("run_id", "node_id");

-- CreateIndex
CREATE INDEX "workflow_steps_run_id_idx" ON "workflow_steps"("run_id");

-- CreateIndex
CREATE INDEX "workflow_steps_run_id_node_id_idx" ON "workflow_steps"("run_id", "node_id");

-- CreateIndex
CREATE INDEX "workflow_human_steps_run_id_idx" ON "workflow_human_steps"("run_id");

-- CreateIndex
CREATE INDEX "workflow_human_steps_status_idx" ON "workflow_human_steps"("status");

-- CreateIndex
CREATE UNIQUE INDEX "workflow_templates_webhook_token_key" ON "workflow_templates"("webhook_token");

-- CreateIndex
CREATE UNIQUE INDEX "workflow_templates_team_id_name_key" ON "workflow_templates"("team_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "workflow_template_versions_template_id_version_key" ON "workflow_template_versions"("template_id", "version");

-- CreateIndex
CREATE INDEX "provider_credentials_provider_scope_team_id_idx" ON "provider_credentials"("provider", "scope", "team_id");

-- CreateIndex
CREATE INDEX "provider_credentials_provider_scope_org_id_idx" ON "provider_credentials"("provider", "scope", "org_id");

-- CreateIndex
CREATE INDEX "provider_credentials_team_id_idx" ON "provider_credentials"("team_id");

-- CreateIndex
CREATE INDEX "provider_credentials_org_id_idx" ON "provider_credentials"("org_id");

-- CreateIndex
CREATE INDEX "config_settings_key_idx" ON "config_settings"("key");

-- CreateIndex
CREATE INDEX "config_settings_scope_team_id_idx" ON "config_settings"("scope", "team_id");

-- CreateIndex
CREATE INDEX "config_settings_scope_org_id_idx" ON "config_settings"("scope", "org_id");

-- CreateIndex
CREATE INDEX "config_settings_scope_channel_id_idx" ON "config_settings"("scope", "channel_id");

-- CreateIndex
CREATE INDEX "config_settings_scope_workflow_template_id_idx" ON "config_settings"("scope", "workflow_template_id");

-- CreateIndex
CREATE INDEX "config_settings_team_id_idx" ON "config_settings"("team_id");

-- CreateIndex
CREATE INDEX "config_settings_org_id_idx" ON "config_settings"("org_id");

-- CreateIndex
CREATE INDEX "config_settings_channel_id_idx" ON "config_settings"("channel_id");

-- CreateIndex
CREATE INDEX "config_settings_workflow_template_id_idx" ON "config_settings"("workflow_template_id");

-- CreateIndex
CREATE INDEX "config_permissions_user_id_idx" ON "config_permissions"("user_id");

-- CreateIndex
CREATE INDEX "config_permissions_role_idx" ON "config_permissions"("role");

-- CreateIndex
CREATE INDEX "config_permissions_team_id_idx" ON "config_permissions"("team_id");

-- CreateIndex
CREATE INDEX "config_permissions_org_id_idx" ON "config_permissions"("org_id");

-- CreateIndex
CREATE INDEX "config_audit_log_entity_type_entity_id_idx" ON "config_audit_log"("entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "config_audit_log_actor_id_idx" ON "config_audit_log"("actor_id");

-- CreateIndex
CREATE INDEX "skills_scope_team_id_idx" ON "skills"("scope", "team_id");

-- CreateIndex
CREATE INDEX "skills_scope_org_id_idx" ON "skills"("scope", "org_id");

-- CreateIndex
CREATE INDEX "skills_team_id_idx" ON "skills"("team_id");

-- CreateIndex
CREATE INDEX "skills_org_id_idx" ON "skills"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "scanner_patterns_label_key" ON "scanner_patterns"("label");

-- CreateIndex
CREATE INDEX "agents_scope_team_id_idx" ON "agents"("scope", "team_id");

-- CreateIndex
CREATE INDEX "agents_scope_org_id_idx" ON "agents"("scope", "org_id");

-- CreateIndex
CREATE INDEX "agents_scope_channel_id_idx" ON "agents"("scope", "channel_id");

-- CreateIndex
CREATE INDEX "agents_scope_workflow_template_id_idx" ON "agents"("scope", "workflow_template_id");

-- CreateIndex
CREATE INDEX "agents_team_id_idx" ON "agents"("team_id");

-- CreateIndex
CREATE INDEX "agents_org_id_idx" ON "agents"("org_id");

-- CreateIndex
CREATE INDEX "agents_channel_id_idx" ON "agents"("channel_id");

-- CreateIndex
CREATE INDEX "agents_workflow_template_id_idx" ON "agents"("workflow_template_id");

-- CreateIndex
CREATE UNIQUE INDEX "agent_skill_refs_agent_id_skill_id_key" ON "agent_skill_refs"("agent_id", "skill_id");

-- CreateIndex
CREATE INDEX "workflow_shell_audit_template_version_id_idx" ON "workflow_shell_audit"("template_version_id");

-- CreateIndex
CREATE INDEX "workflow_shell_audit_team_id_idx" ON "workflow_shell_audit"("team_id");

-- CreateIndex
CREATE UNIQUE INDEX "installed_bundles_name_key" ON "installed_bundles"("name");

-- AddForeignKey
ALTER TABLE "active_workflows" ADD CONSTRAINT "active_workflows_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "run_inputs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "active_workflows" ADD CONSTRAINT "active_workflows_repo_id_fkey" FOREIGN KEY ("repo_id") REFERENCES "connections"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_workflow_id_fkey" FOREIGN KEY ("workflow_id") REFERENCES "active_workflows"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_repo_id_fkey" FOREIGN KEY ("repo_id") REFERENCES "connections"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_workflow_run_id_fkey" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "context_snapshots" ADD CONSTRAINT "context_snapshots_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "run_inputs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pull_requests" ADD CONSTRAINT "pull_requests_workflow_id_fkey" FOREIGN KEY ("workflow_id") REFERENCES "active_workflows"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pull_requests" ADD CONSTRAINT "pull_requests_repo_id_fkey" FOREIGN KEY ("repo_id") REFERENCES "connections"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "personal_access_tokens" ADD CONSTRAINT "personal_access_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "connections" ADD CONSTRAINT "connections_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teams" ADD CONSTRAINT "teams_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_memberships" ADD CONSTRAINT "team_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_memberships" ADD CONSTRAINT "team_memberships_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "org_monthly_usage" ADD CONSTRAINT "org_monthly_usage_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slack_workspaces" ADD CONSTRAINT "slack_workspaces_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slack_channels" ADD CONSTRAINT "slack_channels_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "slack_workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slack_channels" ADD CONSTRAINT "slack_channels_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slack_channels" ADD CONSTRAINT "slack_channels_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "channel_thread_sessions" ADD CONSTRAINT "channel_thread_sessions_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "channel_open_items" ADD CONSTRAINT "channel_open_items_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "channel_monthly_usage" ADD CONSTRAINT "channel_monthly_usage_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "channel_budget_holds" ADD CONSTRAINT "channel_budget_holds_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "run_inputs" ADD CONSTRAINT "run_inputs_connection_id_fkey" FOREIGN KEY ("connection_id") REFERENCES "connections"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "run_inputs" ADD CONSTRAINT "run_inputs_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scheduled_work_requests" ADD CONSTRAINT "scheduled_work_requests_repo_id_fkey" FOREIGN KEY ("repo_id") REFERENCES "connections"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scheduled_work_requests" ADD CONSTRAINT "scheduled_work_requests_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "workflow_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scheduled_work_requests" ADD CONSTRAINT "scheduled_work_requests_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scheduled_work_requests" ADD CONSTRAINT "scheduled_work_requests_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "run_inputs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_artifacts" ADD CONSTRAINT "workflow_artifacts_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_runs" ADD CONSTRAINT "workflow_runs_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "workflow_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_runs" ADD CONSTRAINT "workflow_runs_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "run_inputs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eval_results" ADD CONSTRAINT "eval_results_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eval_results" ADD CONSTRAINT "eval_results_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "eval_cases"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eval_results" ADD CONSTRAINT "eval_results_eval_run_id_fkey" FOREIGN KEY ("eval_run_id") REFERENCES "eval_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eval_cases" ADD CONSTRAINT "eval_cases_dataset_id_fkey" FOREIGN KEY ("dataset_id") REFERENCES "eval_datasets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eval_runs" ADD CONSTRAINT "eval_runs_dataset_id_fkey" FOREIGN KEY ("dataset_id") REFERENCES "eval_datasets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_traces" ADD CONSTRAINT "agent_traces_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_steps" ADD CONSTRAINT "workflow_steps_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_human_steps" ADD CONSTRAINT "workflow_human_steps_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "workflow_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_human_steps" ADD CONSTRAINT "workflow_human_steps_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_templates" ADD CONSTRAINT "workflow_templates_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_template_versions" ADD CONSTRAINT "workflow_template_versions_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_credentials" ADD CONSTRAINT "provider_credentials_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_credentials" ADD CONSTRAINT "provider_credentials_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "embedding_configs" ADD CONSTRAINT "embedding_configs_credential_id_fkey" FOREIGN KEY ("credential_id") REFERENCES "provider_credentials"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_settings" ADD CONSTRAINT "config_settings_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_settings" ADD CONSTRAINT "config_settings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_settings" ADD CONSTRAINT "config_settings_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_settings" ADD CONSTRAINT "config_settings_workflow_template_id_fkey" FOREIGN KEY ("workflow_template_id") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_permissions" ADD CONSTRAINT "config_permissions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_permissions" ADD CONSTRAINT "config_permissions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "config_permissions" ADD CONSTRAINT "config_permissions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skills" ADD CONSTRAINT "skills_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skills" ADD CONSTRAINT "skills_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "slack_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_workflow_template_id_fkey" FOREIGN KEY ("workflow_template_id") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_credential_id_fkey" FOREIGN KEY ("credential_id") REFERENCES "provider_credentials"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agents" ADD CONSTRAINT "agents_mcp_connection_id_fkey" FOREIGN KEY ("mcp_connection_id") REFERENCES "connections"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_skill_refs" ADD CONSTRAINT "agent_skill_refs_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_skill_refs" ADD CONSTRAINT "agent_skill_refs_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_shell_audit" ADD CONSTRAINT "workflow_shell_audit_template_version_id_fkey" FOREIGN KEY ("template_version_id") REFERENCES "workflow_template_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_shell_audit" ADD CONSTRAINT "workflow_shell_audit_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

