import { prisma } from '@auto-swe/shared/db';
import type { RepoWorkRequest, CodeResult } from '@auto-swe/shared/types/workflow';

export async function createOrUpdatePullRequest(
  request: RepoWorkRequest,
  codeResult: CodeResult,
): Promise<{ prNumber: number; prUrl: string }> {
  const { Octokit } = await import('@octokit/rest');

  const repo = await prisma.repository.findUniqueOrThrow({
    where: { id: request.repoId },
  });

  const githubApiUrl = repo.githubApiUrl ?? process.env.GITHUB_API_URL ?? undefined;
  const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN,
    ...(githubApiUrl && { baseUrl: githubApiUrl }),
  });

  // Check if PR already exists
  const existingPR = await prisma.pullRequest.findFirst({
    where: {
      repoId: repo.id,
      workflow: { workRequestId: request.workRequestId },
      status: 'OPEN',
    },
  });

  if (existingPR) {
    await prisma.pullRequest.update({
      where: { id: existingPR.id },
      data: { headSha: codeResult.headSha },
    });

    const githubUrl = repo.githubUrl ?? process.env.GITHUB_URL ?? 'https://github.com';
    return {
      prNumber: existingPR.prNumber!,
      prUrl: `${githubUrl}/${repo.organizationName}/${repo.repoName}/pull/${existingPR.prNumber}`,
    };
  }

  // Create new PR
  const { data: pr } = await octokit.pulls.create({
    owner: repo.organizationName,
    repo: repo.repoName,
    title: formatPRTitle(request),
    body: formatPRBody(request, codeResult),
    head: codeResult.branch,
    base: repo.defaultBranch,
  });

  const workflow = await prisma.activeWorkflow.findFirst({
    where: { workRequestId: request.workRequestId },
  });

  await prisma.pullRequest.create({
    data: {
      prNumber: pr.number,
      headSha: codeResult.headSha,
      status: 'OPEN',
      ciStatus: 'PENDING',
      repoId: repo.id,
      workflowId: workflow?.id,
    },
  });

  return { prNumber: pr.number, prUrl: pr.html_url };
}

// ── Configurable PR Title & Body ──

const DEFAULT_PR_TITLE_TEMPLATE = '[auto-swe] {{ticketId}}';

const DEFAULT_PR_BODY_TEMPLATE = `## {{ticketId}}

**Description:** {{description}}
**Test Status:** {{testStatus}}
**Files Changed:** {{filesChanged}}

### Changes
{{fileList}}

### Agent Notes
{{notes}}

---
_Generated by auto-swe_`;

function formatPRTitle(request: RepoWorkRequest): string {
  const template = process.env.PR_TITLE_TEMPLATE ?? DEFAULT_PR_TITLE_TEMPLATE;
  return template
    .replace(/\{\{ticketId\}\}/g, request.externalTicketId)
    .replace(/\{\{description\}\}/g, request.description);
}

function formatPRBody(request: RepoWorkRequest, codeResult: CodeResult): string {
  const testStatus = codeResult.testResults.passed
    ? `All tests passing (${codeResult.testResults.passing}/${codeResult.testResults.total})`
    : `Tests failing (${codeResult.testResults.passing}/${codeResult.testResults.total} passing)`;

  const fileList = codeResult.filesChanged
    .map((f) => `- \`${f.path}\` (${f.operation}, +${f.linesAdded}/-${f.linesRemoved})`)
    .join('\n');

  const template = process.env.PR_BODY_TEMPLATE ?? DEFAULT_PR_BODY_TEMPLATE;
  return template
    .replace(/\{\{ticketId\}\}/g, request.externalTicketId)
    .replace(/\{\{description\}\}/g, request.description)
    .replace(/\{\{branch\}\}/g, codeResult.branch)
    .replace(/\{\{testStatus\}\}/g, testStatus)
    .replace(/\{\{filesChanged\}\}/g, String(codeResult.filesChanged.length))
    .replace(/\{\{fileList\}\}/g, fileList)
    .replace(/\{\{notes\}\}/g, codeResult.implementationNotes);
}
