import { prisma } from '@auto-swe/shared/db';
import { resolveGitHubConfig, resolveWorkflowDefaults } from '@auto-swe/shared/lib/systemConfig';
import type { CodeResult, RepoWorkRequest } from '@auto-swe/shared/types/workflow';
import { ApplicationFailure, activityInfo } from '@temporalio/activity';
import { persistActivityTrace } from '../lib/activityContext.js';
import { AgentTracer } from '../lib/agentTracer.js';
import { notifySlackPrReady } from '../lib/slackNotify.js';

export async function createOrUpdatePullRequest(
  request: RepoWorkRequest,
  codeResult: CodeResult
): Promise<{ prNumber: number; prUrl: string }> {
  const { Octokit } = await import('@octokit/rest');
  const tracer = new AgentTracer();

  const repo = await prisma.repository.findUniqueOrThrow({
    where: { id: request.repoId },
  });

  const [ghConfig, workflowDefaults] = await Promise.all([
    resolveGitHubConfig(),
    resolveWorkflowDefaults(),
  ]);
  if (!ghConfig.token)
    throw ApplicationFailure.nonRetryable(
      'GitHub token not configured. Set it at /admin/integrations.',
      'CONFIG_MISSING'
    );
  const githubApiUrl =
    repo.githubApiUrl ??
    (ghConfig.apiUrl !== 'https://api.github.com' ? ghConfig.apiUrl : undefined);
  const octokit = new Octokit({
    auth: ghConfig.token,
    ...(githubApiUrl && { baseUrl: githubApiUrl }),
  });

  // Check if PR already exists
  const existingPR = await prisma.pullRequest.findFirst({
    where: {
      repoId: repo.id,
      status: 'OPEN',
      workflow: { workRequestId: request.workRequestId },
    },
  });

  if (existingPR) {
    if (existingPR.prNumber == null) {
      throw ApplicationFailure.nonRetryable(
        `PR record ${existingPR.id} exists but has no prNumber — cannot build PR URL`,
        'PR_MISSING_NUMBER'
      );
    }

    await prisma.pullRequest.update({
      data: { headSha: codeResult.headSha },
      where: { id: existingPR.id },
    });

    const githubUrl = repo.githubUrl ?? ghConfig.baseUrl;
    const prUrl = `${githubUrl}/${repo.organizationName}/${repo.repoName}/pull/${existingPR.prNumber}`;
    tracer.addActivityEvent({
      name: 'pr.updated',
      outputJson: {
        branch: codeResult.branch,
        headSha: codeResult.headSha,
        prNumber: existingPR.prNumber,
        prUrl,
      },
    });
    await persistActivityTrace(tracer, 'pr');
    return { prNumber: existingPR.prNumber, prUrl };
  }

  // Reuse an already-open PR for this head branch if GitHub has one. This makes
  // the activity idempotent across Temporal retries: if a prior attempt created
  // the PR on GitHub but crashed before persisting the DB row, the retry finds
  // it here instead of failing with GitHub's 422 "a pull request already exists
  // for this branch" — and still writes the tracking row below. Only a prior
  // attempt could have orphaned a PR, so we skip this extra GitHub round-trip on
  // the first attempt and create directly.
  const priorOpenPr =
    activityInfo().attempt > 1
      ? (
          await octokit.pulls.list({
            base: repo.defaultBranch,
            head: `${repo.organizationName}:${codeResult.branch}`,
            owner: repo.organizationName,
            repo: repo.repoName,
            state: 'open',
          })
        ).data[0]
      : undefined;

  const pr =
    priorOpenPr ??
    (
      await octokit.pulls.create({
        base: repo.defaultBranch,
        body: formatPRBody(request, codeResult, workflowDefaults.prBodyTemplate || undefined),
        head: codeResult.branch,
        owner: repo.organizationName,
        repo: repo.repoName,
        title: formatPRTitle(request, workflowDefaults.prTitleTemplate),
      })
    ).data;

  const workflow = await prisma.activeWorkflow.findFirst({
    where: { workRequestId: request.workRequestId },
  });

  await prisma.pullRequest.create({
    data: {
      ciStatus: 'PENDING',
      headSha: codeResult.headSha,
      prNumber: pr.number,
      repoId: repo.id,
      status: 'OPEN',
      workflowId: workflow?.id,
    },
  });

  // Best-effort: let the originating Slack channel know the PR is open.
  await notifySlackPrReady({
    prNumber: pr.number,
    prUrl: pr.html_url,
    workRequestId: request.workRequestId,
  });

  tracer.addActivityEvent({
    name: 'pr.created',
    outputJson: {
      branch: codeResult.branch,
      headSha: codeResult.headSha,
      prNumber: pr.number,
      prUrl: pr.html_url,
    },
  });
  await persistActivityTrace(tracer, 'pr');

  return { prNumber: pr.number, prUrl: pr.html_url };
}

// ── Configurable PR Title & Body ──

const DEFAULT_PR_TITLE_TEMPLATE = '[auto-swe] {{ticketId}}';

const DEFAULT_PR_BODY_TEMPLATE = `## {{ticketId}}

**Description:** {{description}}
**Test Status:** {{testStatus}}
**Files Changed:** {{filesChanged}}

### Changes
{{fileList}}

### Agent Notes
{{notes}}

---
_Generated by auto-swe_`;

function formatPRTitle(request: RepoWorkRequest, titleTemplate?: string): string {
  const template = titleTemplate ?? DEFAULT_PR_TITLE_TEMPLATE;
  // Function replacers so `$`-sequences in the values (e.g. `$1`, `$&`) are
  // inserted literally rather than interpreted as replacement patterns.
  return template
    .replace(/\{\{ticketId\}\}/g, () => request.externalTicketId)
    .replace(/\{\{description\}\}/g, () => request.description);
}

function formatPRBody(
  request: RepoWorkRequest,
  codeResult: CodeResult,
  bodyTemplate?: string
): string {
  const testStatus = codeResult.testResults.passed
    ? `All tests passing (${codeResult.testResults.passing}/${codeResult.testResults.total})`
    : `Tests failing (${codeResult.testResults.passing}/${codeResult.testResults.total} passing)`;

  const fileList = codeResult.filesChanged
    .map((f) => `- \`${f.path}\` (${f.operation}, +${f.linesAdded}/-${f.linesRemoved})`)
    .join('\n');

  const template = bodyTemplate || DEFAULT_PR_BODY_TEMPLATE;
  // Function replacers so `$`-sequences in agent-authored text (description,
  // notes, file paths) are inserted literally, not treated as `$1`/`$&` patterns.
  return template
    .replace(/\{\{ticketId\}\}/g, () => request.externalTicketId)
    .replace(/\{\{description\}\}/g, () => request.description)
    .replace(/\{\{branch\}\}/g, () => codeResult.branch)
    .replace(/\{\{testStatus\}\}/g, () => testStatus)
    .replace(/\{\{filesChanged\}\}/g, () => String(codeResult.filesChanged.length))
    .replace(/\{\{fileList\}\}/g, () => fileList)
    .replace(/\{\{notes\}\}/g, () => codeResult.implementationNotes);
}
