import { ACCEPTANCE_CRITERIA_FIRST_SKILL } from './acceptanceCriteriaFirst.js';
import { ACTIONABLE_LESSONS_SKILL } from './actionableLessons.js';
import { API_CONTRACT_STABILITY_SKILL } from './apiContractStability.js';
import { ASYNC_SAFETY_SKILL } from './asyncSafety.js';
import { CONFIGURATION_OVER_HARDCODING_SKILL } from './configurationOverHardcoding.js';
import { CONTEXT_AMBIGUITY_RESOLUTION_SKILL } from './contextAmbiguityResolution.js';
import { DESIGN_FIDELITY_SKILL } from './designFidelity.js';
import { DOMAIN_LOGIC_INTEGRITY_SKILL } from './domainLogicIntegrity.js';
import { ERROR_PATH_COVERAGE_SKILL } from './errorPathCoverage.js';
import { FOLLOW_EXISTING_PATTERNS_SKILL } from './followExistingPatterns.js';
import { GRACEFUL_DEGRADATION_SKILL } from './gracefulDegradation.js';
import { IDEMPOTENCY_SKILL } from './idempotency.js';
import { INCREMENTAL_COMMITS_SKILL } from './incrementalCommits.js';
import { MIGRATION_SAFETY_REVIEW_SKILL } from './migrationSafetyReview.js';
import { MINIMAL_SURFACE_AREA_SKILL } from './minimalSurfaceArea.js';
import { NO_NEW_DEPENDENCIES_SKILL } from './noNewDependencies.js';
import { OBSERVABILITY_FIRST_SKILL } from './observabilityFirst.js';
import { PERFORMANCE_IMPACT_ASSESSMENT_SKILL } from './performanceImpactAssessment.js';
import { PR_DESCRIPTION_QUALITY_SKILL } from './prDescriptionQuality.js';
import { REVIEW_FOCUS_SECURITY_SKILL } from './reviewFocusSecurity.js';
import { ROLLBACK_FIRST_PLANNING_SKILL } from './rollbackFirstPlanning.js';
import { SCOPE_CONSERVATISM_SKILL } from './scopeConservatism.js';
import { SECURITY_AWARE_IMPLEMENTATION_SKILL } from './securityAwareImplementation.js';
import { SECURITY_REVIEW_DEPTH_SKILL } from './securityReviewDepth.js';
import { SHELL_COMMAND_SAFETY_SKILL } from './shellCommandSafety.js';
import { SUBTASK_DECOMPOSITION_SKILL } from './subtaskDecomposition.js';
import { SUCCESS_CRITERIA_EXTRACTION_SKILL } from './successCriteriaExtraction.js';
import { TEST_FIRST_SKILL } from './testFirst.js';

export interface BuiltinSkillDef {
  name: string;
  description: string;
  promptText: string;
  assignments: { role: string; sortOrder: number }[];
}

export const BUILTIN_SKILLS: BuiltinSkillDef[] = [
  // Implementer skills
  SCOPE_CONSERVATISM_SKILL,
  FOLLOW_EXISTING_PATTERNS_SKILL,
  TEST_FIRST_SKILL,
  INCREMENTAL_COMMITS_SKILL,
  NO_NEW_DEPENDENCIES_SKILL,
  SHELL_COMMAND_SAFETY_SKILL,
  SECURITY_AWARE_IMPLEMENTATION_SKILL,
  ERROR_PATH_COVERAGE_SKILL,
  ACCEPTANCE_CRITERIA_FIRST_SKILL,
  IDEMPOTENCY_SKILL,
  GRACEFUL_DEGRADATION_SKILL,
  ASYNC_SAFETY_SKILL,
  OBSERVABILITY_FIRST_SKILL,
  MINIMAL_SURFACE_AREA_SKILL,
  CONFIGURATION_OVER_HARDCODING_SKILL,
  ROLLBACK_FIRST_PLANNING_SKILL,
  DESIGN_FIDELITY_SKILL,
  // Reviewer skills (shared role)
  REVIEW_FOCUS_SECURITY_SKILL,
  MIGRATION_SAFETY_REVIEW_SKILL,
  API_CONTRACT_STABILITY_SKILL,
  // Sub-reviewer skills (targeted roles)
  SECURITY_REVIEW_DEPTH_SKILL,
  DOMAIN_LOGIC_INTEGRITY_SKILL,
  PERFORMANCE_IMPACT_ASSESSMENT_SKILL,
  // Planner / decomposer skills
  PR_DESCRIPTION_QUALITY_SKILL,
  SUBTASK_DECOMPOSITION_SKILL,
  // validateContext skills
  SUCCESS_CRITERIA_EXTRACTION_SKILL,
  CONTEXT_AMBIGUITY_RESOLUTION_SKILL,
  // commitToMemory skills
  ACTIONABLE_LESSONS_SKILL,
];

export {
  ACCEPTANCE_CRITERIA_FIRST_SKILL,
  ACTIONABLE_LESSONS_SKILL,
  API_CONTRACT_STABILITY_SKILL,
  ASYNC_SAFETY_SKILL,
  CONFIGURATION_OVER_HARDCODING_SKILL,
  CONTEXT_AMBIGUITY_RESOLUTION_SKILL,
  DESIGN_FIDELITY_SKILL,
  DOMAIN_LOGIC_INTEGRITY_SKILL,
  ERROR_PATH_COVERAGE_SKILL,
  FOLLOW_EXISTING_PATTERNS_SKILL,
  GRACEFUL_DEGRADATION_SKILL,
  IDEMPOTENCY_SKILL,
  INCREMENTAL_COMMITS_SKILL,
  MIGRATION_SAFETY_REVIEW_SKILL,
  MINIMAL_SURFACE_AREA_SKILL,
  NO_NEW_DEPENDENCIES_SKILL,
  OBSERVABILITY_FIRST_SKILL,
  PERFORMANCE_IMPACT_ASSESSMENT_SKILL,
  PR_DESCRIPTION_QUALITY_SKILL,
  REVIEW_FOCUS_SECURITY_SKILL,
  ROLLBACK_FIRST_PLANNING_SKILL,
  SCOPE_CONSERVATISM_SKILL,
  SECURITY_AWARE_IMPLEMENTATION_SKILL,
  SECURITY_REVIEW_DEPTH_SKILL,
  SHELL_COMMAND_SAFETY_SKILL,
  SUBTASK_DECOMPOSITION_SKILL,
  SUCCESS_CRITERIA_EXTRACTION_SKILL,
  TEST_FIRST_SKILL,
};
